### ISSUE TITLE
Error in Iphone 6 plus

### ISSUE THREAD

**Issue by kirill001** [dzcpy/transliteration#82] opened 2018-09-14 12:25 UTC
Hello,
Thank you! Your module works perfect for me, but one of our clients has an error when I use your module on my website.
Here is a screenshot of that error
![photo_2018-09-14_14-22-22](https://user-images.githubusercontent.com/8287881/45549944-ca2e4500-b829-11e8-9f97-4f4c4e0f000e.jpg)
He has an error in safari and chrome, so now he can't use my website.
I can't reproduce the error with my devices, but I'm afraid that other users have the same errors.

**Comment by andyhu** [comment] 2018-10-21 11:50
Sorry for the late reply. Is there still any issues? I kind of think that this issue is caused by other libraries like Bootstrap, rather than transliteration. I'll first close this issue. If you can provide more details about how to reproduce it, I'll reopen it.

**Closed** 2019-01-11 14:02 UTC
