### ISSUE TITLE
Can't resolve "core-js" dependency. [BUG]

### ISSUE THREAD

**Issue by igocooper** [dzcpy/transliteration#102] opened 2019-06-24 12:58 UTC
Hi there, so here is my issue. 

I'm having package A which has `transliteration` as a dependency. And there is also package B, which has package A as a dependency. Once I'm building package A with webpack build is broken and i'm getting this error: 

`ERROR in ./node_modules/package-a/node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.sort' in '/Users/igocooper/Projects/package-b/node_modules/package-a/node_modules/transliteration/dist/browser'` 

As a temporary workaround i've downgraded to v. 2.0.0 and it's working fine. Was there any changes between 2.0.0 - 2.1.0 which might affect this?

**Comment by dzcpy** [comment] 2019-06-27 10:23
Can you please try version `2.1.4`? I believe it should be fixed.

**Comment by lynx-r** [comment] 2019-06-27 14:19
No, it is not fixed in 2.1.4

**Comment by dzcpy** [comment] 2019-06-27 15:15
@lynx-r Could you elaborate? How can you reproduce the issue?

**Comment by lynx-r** [comment] 2019-06-28 04:42
Maybe this is an another bug but I got the errors after installing the package like:

```
npm i transliteration
```

Then I imported `slugify` like this:

```
import { slugify } from 'transliteration';
```

And when I restarted my project I got a bunch of the errors:

```

ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/a-function' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/advance-string-index' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/an-object' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/array-for-each' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/array-includes' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/array-iteration' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/array-method-has-species-support' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/create-property' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/descriptors' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/dom-iterables' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/export' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/fails' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/fix-regexp-well-known-symbol-logic' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/forced-string-trim-method' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/global' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/hide' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/indexed-object' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/inherit-if-required' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/is-array' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/is-forced' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/is-object' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/is-regexp' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/object-assign' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/object-define-property' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/object-get-own-property-names' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/object-keys' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/redefine' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/regexp-exec' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/regexp-exec-abstract' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/regexp-flags' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/require-object-coercible' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/set-species' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/sloppy-array-method' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/string-trim' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/to-absolute-index' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/to-indexed-object' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/to-integer' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/to-length' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/to-object' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
ERROR in ./node_modules/transliteration/dist/browser/bundle.umd.min.js
Module not found: Error: Can't resolve '../internals/well-known-symbol' in '/Users/aleksey/IdeaProjects/mahuru/iwow/admin/node_modules/transliteration/dist/browser'
```

**Comment by retorquere** [comment] 2019-06-28 14:22
I'm seeing the same error as @lynx-r when I upgraded from 2.1.3 to 2.1.4. Downgrading to 2.1.3 fixes it for me.

**Comment by zobzn** [comment] 2019-06-28 20:36
I confirm the error after upgrading from 2.1.3 to 2.1.4.

**Comment by kattergil** [comment] 2019-06-29 11:29
Me either. same error as @lynx-r. and also working well after downgrade to 2.1.3 as @zobzn said.

**Comment by zobzn** [comment] 2019-06-29 21:04
I tried to fix the error - https://github.com/dzcpy/transliteration/pull/106

**Comment by retorquere** [comment] 2019-06-30 06:01
How would I test whether this works for me?

**Comment by zobzn** [comment] 2019-06-30 06:12
@igocooper I believe breaking change appeared between 2.0.3 and 2.0.4.
At least if you compare https://cdn.jsdelivr.net/npm/transliteration@2.0.3/dist/browser/bundle.umd.min.js and https://cdn.jsdelivr.net/npm/transliteration@2.0.4/dist/browser/bundle.umd.min.js, you can notice that 2.0.4 contains require("core-js/modules/es6.regexp.replace") and so on, which indicates that rollup didn't include core-js files in the final build.

**Comment by retorquere** [comment] 2019-07-08 07:49
@zobzn but in 2.1.3 it worked again, so even if it was a regression between 2.0.3 and 2.0.4, it's also a regression between 2.1.3 and 2.1.4.

**Comment by retorquere** [comment] 2019-07-08 07:54
`import { transliterate } from 'transliteration/dist/node/src/node'` works for me on 2.1.4 as a workaround.

**Comment by vitaliyhayda** [comment] 2019-07-10 22:24
similar error for me, temporarily fixed as mentioned by @retorquere

**Comment by dzcpy** [comment] 2019-08-01 16:52
Should be fixed in #106, thanks @zobzn for the PR

**Comment by retorquere** [comment] 2019-08-01 17:12
Can we get a comment here when this is published in a new release? Then I can undo my workaround.

**Comment by retorquere** [comment] 2019-08-01 18:31
Oh wait it's already out as 2.1.5

**Comment by dzcpy** [comment] 2019-08-06 11:40
Closing this one, let me know if there's still an issue

**Closed by dzcpy** 2019-08-06 11:40 UTC
