### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by vitaliyhayda** [dzcpy/transliteration#91] opened 2019-01-15 13:00 UTC
In any v2 version I'm getting:

    Uncaught TypeError: Object(...) is not a function

With this simple example:

    import { transliterate } from 'transliteration';
    console.log(transliterate('bla bla'));

-------

_no issues in 1.6.6_

**Comment by dzcpy** [comment] 2019-01-16 03:31
Hi, where did you see this error, in the browser or node.js? What's your browser / node.js version?

**Comment by dzcpy** [comment] 2019-01-16 21:48
I've tested your code under both node.js + babel with preset-env and typescript. Can't reproduce your issue. I'll close it now but if you could elaborate how to reproduce it, feel free to open it again.

**Closed** 2019-01-16 21:48 UTC

**Comment by vitaliyhayda** [comment] 2019-01-21 13:04
works now 👍
